# Profil prod pour Render - force l'URL JDBC avec le bon préfixe
spring.datasource.url=jdbc:postgresql://dpg-d9mpcj7qj5pc73dglblg-a.frankfurt-postgres.render.com/air_groupe_db
spring.datasource.username=air_groupe_db_user
spring.datasource.password=JQl0LznHsvnMMAxQU8RQ8GwrFVVZbhJn

# Désactiver Flyway temporairement (vous pourrez le réactiver plus tard)
spring.flyway.enabled=false